### ISSUE TITLE
Please Upgrade for Kirby 3 ASAP! 😊

### ISSUE THREAD

**Issue by luxlogica** [olach/kirby-relationship#10]

**Comment by olach** [comment]
Don’t worry. This plugin will be upgraded for Kirby 3.

I’m currently following the development of Kirby 3, and as soon as the plugin API has been stabilized and they have added proper docs, I will start to upgrade this plugin.

My plan is to have it ready during the beta period, before the official release of Kirby 3 later this year.

**Comment by luxlogica** [comment]
@olach I believe the plugin API as been stabilised sufficiently for plugin authors to start porting their plugins across - and the beta period has already started... ;-)

**Comment by olach** [comment]
Last time I checked they had problem with their bundled drag-n-drop library and they were looking for a replacement library. Don’t know if they have bundled a new one yet that plugins can use. Will check that out when I’m back from my vacation.

**Comment by luxlogica** [comment]
@olach Enjoy your vacation!!! 🏖

It seems that they have just finished implementing drag-and-drop from image lists directly into textarea fields, so I'd say drag-and-drop must be sorted!
