### ISSUE TITLE
Class 'CheckboxesField' not found

### ISSUE THREAD

**Issue by felipep** [olach/kirby-relationship#11]
I cannot use this Plugin, I get the following error `Whoops \ Exception \ ErrorException (E_ERROR)
Class 'CheckboxesField' not found`

kirby-relationship from branch master
My environment PHP 7.1
Kirby 2.5.11

**Comment by olach** [comment]
This field extends the regular Checkboxes field that ships with Kirby. The error message says this field is not found, which is strange. It seems to either be a problem with your Kirby installation, or the plugin is not installed correctly. 

Can you please try to install a fresh copy of Kirby with this plugin and see if it works?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by olach** [comment]
Closing this issue because of no response.
