### ISSUE TITLE
Selected items counter

### ISSUE THREAD

**Issue by antoine1000** [olach/kirby-relationship#12]
First, thanks for this really useful plugin !

I was thinking that it could be nice to have an item counter to know how much items are selected in the relationship field.

If have I some time I'll try to add this feature, if some people find it useful.

**Comment by olach** [comment]
Thanks! You're right, this could be a useful feature. Another request is to have a min/max setting.

Right now I'm working to convert this plugin for the upcoming Kirby 3. After that, I might consider adding some feature request to this version also.

**Comment by olach** [comment]
I just published an update to the develop branch with this feature (and min/max validation) that you can try out.

**Comment by olach** [comment]
I just released a new version with this feature added. To show the counter, add `counter: true` to the blueprint for the field.
