### ISSUE TITLE
Search/Filter functionality

### ISSUE THREAD

**Issue by medienbaecker** [olach/kirby-relationship#2]
Love this field! ❤️ 

Maybe it would make sense to add an optional search/filter bar on the top for more complex applications? When there are a lot of "related pages" to choose from, for example.

**Comment by olach** [comment]
You read my mind. 😄 That is exactly the next feature I wish to implement.

**Comment by fenixkim** [comment]
+1

**Comment by olach** [comment]
I have implemented a simple search functionality that you can find in the `feature/search` branch. I have pushed this to a site for a client of mine to test. If all goes well I will push it to master in a couple of days.

**Comment by medienbaecker** [comment]
Looks great!
One thing I noticed is that you added the page name as a lowercase `data` attribute. So searching for "Contact" will not show the "Contact" page, while "contact" will. You should probably convert the search value to lowercase, too.

**Comment by olach** [comment]
Good find! I have uploaded a fix for this now.

**Comment by olach** [comment]
Optional search field is now added in v1.1.0.

Add `search: true` to the field options to enable search.
