### ISSUE TITLE
Custom Cell Feature

### ISSUE THREAD

**Issue by fenixkim** [olach/kirby-relationship#3]
Is it possible to add an option de customize the cells allowing to show any additional data about the relationship like image previews?

**Comment by olach** [comment]
Not in it's current form. The field is just an extension of the core Checkboxes field. Think of it as a different ui of the Checkboxes field, where you are able manually sort the selected options.

Each option in the Checkboxes field has only two data values: key and value. For example, if I list pages, I get `url` and `title` for each page item.

With that said, it probably should be doable to at least to show an image preview for images. I probably don't have time to look into that for now, but I'll let this issue be open if someone wants to make a PR for that feature request.

If you just want a field that lets you select and sort images to build a gallery, I can recommend this plugin:
https://github.com/medienbaecker/kirby-images

**Comment by fenixkim** [comment]
Ok, I understand you.

In my case I have a lot of pages with products, and a thumbnail would be a great feature together with a search filter (#2).

I going to check the code in order to evaluate a posible PR.

Thanks a lot for your plugin and for your reply!

**Comment by olach** [comment]
I plan to keep this field as simple as possible, without to much bloat. But I gave your suggestion a second thought, and yes, the option to show thumbnails would be a great feature. Especially for your example with products. I have an idea on how to implement this and will have a look at it.

**Comment by olach** [comment]
You can now try out support for thumbnails in the [develop branch](/olach/kirby-relationship/tree/develop). Instructions in the readme.

**Comment by olach** [comment]
Thumbnails are now supported in the latest version just published.
