### ISSUE TITLE
Min & Max items validation

### ISSUE THREAD

**Issue by illycz** [olach/kirby-relationship#4]
Thanks for great plugin!
What about min. max. items validation?

**Comment by olach** [comment]
Thanks! Hmm, yes, maybe that would be an valid option. I plan to keep this field as lightweight as possible, without to much bloat. But I will give your suggestion some thought.

**Comment by illycz** [comment]
Best solution would be implement this validation to core checkboxes field...

**Comment by vasilisakarelova** [comment]
@illycz you can add this function to **relationship.php** file at the end, after **function thumbnail($key) {}**

````
/* Validate max or min amount of selected items */

public function validate() {
    if (!parent::validate()) return false;

    $validators = $this->validate;
    $count = is_array($this->value()) ? count($this->value()) : 0;

    if (is_array($validators)) {
      if (isset($validators['maxItems']) && $count > $validators['maxItems']) {
        return false;
      }
      if (isset($validators['minItems']) && $count < $validators['minItems']) {
        return false;
      }
    }

    return true;
  }
````

**Comment by illycz** [comment]
@vasilisakarelova maybe PR is welcome, I do not want to make changes to plugin which stops update possibilities... Thanks

**Comment by vasilisakarelova** [comment]
it's just a suggestion. in case you need this, and since there were no updates lately

**Comment by olach** [comment]
I will try to find some time to implement this. I think it's a good feature to add.

**Comment by olach** [comment]
I just published an update to the develop branch with this feature that you can try out.

**Comment by olach** [comment]
I just released a new version with this feature added. Check the updated readme for instructions.
