### ISSUE TITLE
Disable field for non-translatable fields

### ISSUE THREAD

**Issue by fenixkim** [olach/kirby-relationship#6]
The field continues being active for fields with the [`translate: false`](https://getkirby.com/docs/panel/blueprints/form-fields#prevent-field-values-in-non-default-languages) option.

I think this is a error, but I would like to confirm this.

Thanks!

**Comment by olach** [comment]
Thanks. I will look into this next week.

**Comment by olach** [comment]
Sorry for the delay, but this is now fixed in the latest version.
