### ISSUE TITLE
Add an image to each option

### ISSUE THREAD

**Issue by jonabaptistella** [olach/kirby-relationship#8]
In my use case that will make this plugin the best. 👍

**Comment by olach** [comment]
I agree! Actually there is already a feature request for this in issue #3.

I will try to implement this in the next version.

**Comment by olach** [comment]
You can now try out new support for thumbnails in the [develop branch](/olach/kirby-relationship/tree/develop). Instructions in the readme.

**Comment by olach** [comment]
Thumbnails are now supported in the latest version just published.
